x-common-settings: &common-settings
  user: 1000:1000
  image: unitree_sim:0.3
  stdin_open: true
  tty: true
  shm_size: 24gb
  hostname: mrob1-Latitude-5491

services:
  develop:
    <<: *common-settings
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/mrob1/Projects:/home/oversir/humanoid_sim
    command: >
      sh -c "
      /home/oversir/humanoid_sim/startup.sh && bash
      "
